### ISSUE TITLE
dubbo-py使用疑问

### ISSUE THREAD

**Issue by sym695989697** [feiyuw/dubbo-py#6]
1．Dubbo-py 注册到zk后 的服务接口可以用java调用 么？
2．测试例子注册到DUBBOADMIN中 关闭程序 怎么注册的服务接口不消失

**Comment by feiyuw** [comment]
1. 可以的
2. 没用过dubbo admin，我现在的注册只是在zk中加了条记录，从逻辑上看，关闭程序，zk中的记录不会自己消除的，但一般应该有保活机制，超时过期的那种，这块没有具体看过。

**Comment by sym695989697** [comment]
> 1. 可以的
> 2. 没用过dubbo admin，我现在的注册只是在zk中加了条记录，从逻辑上看，关闭程序，zk中的记录不会自己消除的，但一般应该有保活机制，超时过期的那种，这块没有具体看过。
java :
package com.hello.consumer;

import com.alibaba.dubbo.config.ApplicationConfig;
import com.alibaba.dubbo.config.ReferenceConfig;
import com.alibaba.dubbo.config.RegistryConfig;
import com.alibaba.dubbo.rpc.service.GenericService;

/**
 * dubbo泛化调用invoker 调用入口
 *
 * @author mazhenjie
 * @since 2019/4/26
 */
public class DubboGenericInvoker {

	public static void main(String[] args) {
		ApplicationConfig application = new ApplicationConfig();
		application.setName("api-generic-consumer");

		RegistryConfig registry = new RegistryConfig();
		registry.setAddress("zookeeper://172.20.30.76:2181");

		application.setRegistry(registry);
		
		ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
		// 弱类型接口名
		reference.setInterface("calc");
		reference.setVersion("1.0.0");
		// 声明为泛化接口
		reference.setGeneric(true);
		reference.setApplication(application);

		// 用com.alibaba.dubbo.rpc.service.GenericService可以替代所有接口引用
		GenericService genericService = reference.get();

		 Object name = genericService.$invoke("multi2", new String[] {int.class.getName()}, new Object[]{2});
		System.out.println(name);
	}
}

================================================================
python:
import time
from dubbo.server import DubboService


def _multi_2_handler(num):
    return num * 2


def _exp_handler(num):
    return num ** 2


if __name__ == '__main__':
    service = DubboService(12358, 'demo')
    service.add_method('calc', 'multi2', _multi_2_handler)
    service.add_method('calc', 'exp', _exp_handler)
    service.register('172.20.30.76:2181')  # register to zookeeper
    service.start()  # service run in a daemon thread
    time.sleep(300)  # after 300 seconds, the service will be stoppe

====================================================
python 报
pydev debugger: starting (pid: 14228)
WARNING:root:no handler for b'calc'.b'$invoke'
WARNING:root:no handler for b'calc'.b'$invoke'
WARNING:root:no handler for b'calc'.b'$invoke'

**Comment by feiyuw** [comment]
duplicated with #7
